# Generated by Django 4.0.3 on 2022-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя собачки', max_length=50, verbose_name='Имя собачки')),
                ('breed', models.CharField(help_text='Укажите породу собачки', max_length=50, verbose_name='Порода собачки')),
            ],
            options={
                'verbose_name': 'Собачка',
                'verbose_name_plural': 'Собачки',
            },
        ),
    ]
