# Generated by Django 4.0.3 on 2022-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя котика', max_length=50, verbose_name='Имя котика')),
                ('breed', models.CharField(help_text='Укажите породу котика', max_length=50, verbose_name='Порода котика')),
            ],
            options={
                'verbose_name': 'Котик',
                'verbose_name_plural': 'Котики',
            },
        ),
    ]
